# redis-db deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.appName.redis }}
    namespace: {{ .Values.namespace }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.appName.redis }}
            role: master
    template:
        metadata:
            labels:
                app: {{ .Values.appName.redis }}
                role: master
        spec:
            volumes:
            - name: redis-storage
              persistentVolumeClaim:
                claimName: redis-pvc
            containers:
                - name: redis-master
                  image: {{ .Values.image.redis }}
                  resources:
                      limits:
                          cpu: 200m
                          memory: 200Mi
                  command:
                      - redis-server
                  args:
                      - --requirepass
                      - $(REDIS_PASSWORD)
                  ports:
                      - containerPort: 6379
                  env:
                  - name: REDIS_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: {{ .Values.secretKey.redis }}
                            key: db_password

---

#redis-db service configuration
apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.appName.redis }}
    namespace: {{ .Values.namespace }}
    labels:
        app: {{ .Values.appName.redis }}
        role: master
spec:
    ports:
        - port: 6379
          targetPort: 6379
    selector:
        app: {{ .Values.appName.redis }}
        role: master
