# Persistent Volume for redis
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentvolume.pv.volumeName }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  capacity:
    storage: {{ .Values.persistentvolume.pv.storageCapacity }}
  hostPath:
    path: /data/redis-pv/

---

#Persistent Volume Claim for redis node
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentvolume.pvc.claimName }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: local-storage
  accessModes:
    - "ReadWriteOnce"
  volumeName: {{ .Values.persistentvolume.pv.volumeName }}
  resources:
    requests:
      storage: {{ .Values.persistentvolume.pvc.storageRequest }}